//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.11 at 11:32:44 PM CEST 
//


package com.jtalis.core.config.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jtalis.core.config.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Config_QNAME = new QName("http://www.w3schools.com", "config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jtalis.core.config.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConfigType }
     * 
     */
    public ConfigType createConfigType() {
        return new ConfigType();
    }

    /**
     * Create an instance of {@link ConsultFilesListType }
     * 
     */
    public ConsultFilesListType createConsultFilesListType() {
        return new ConsultFilesListType();
    }

    /**
     * Create an instance of {@link EventFilesListType }
     * 
     */
    public EventFilesListType createEventFilesListType() {
        return new EventFilesListType();
    }

    /**
     * Create an instance of {@link PredicatesListType }
     * 
     */
    public PredicatesListType createPredicatesListType() {
        return new PredicatesListType();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link EventRuleListType }
     * 
     */
    public EventRuleListType createEventRuleListType() {
        return new EventRuleListType();
    }

    /**
     * Create an instance of {@link EtalisFlagType }
     * 
     */
    public EtalisFlagType createEtalisFlagType() {
        return new EtalisFlagType();
    }

    /**
     * Create an instance of {@link EtalisFlagsListType }
     * 
     */
    public EtalisFlagsListType createEtalisFlagsListType() {
        return new EtalisFlagsListType();
    }

    /**
     * Create an instance of {@link OutputQueueType }
     * 
     */
    public OutputQueueType createOutputQueueType() {
        return new OutputQueueType();
    }

    /**
     * Create an instance of {@link EventRuleType }
     * 
     */
    public EventRuleType createEventRuleType() {
        return new EventRuleType();
    }

    /**
     * Create an instance of {@link EventTriggersListType }
     * 
     */
    public EventTriggersListType createEventTriggersListType() {
        return new EventTriggersListType();
    }

    /**
     * Create an instance of {@link OutputQueuesListType }
     * 
     */
    public OutputQueuesListType createOutputQueuesListType() {
        return new OutputQueuesListType();
    }

    /**
     * Create an instance of {@link ProviderType }
     * 
     */
    public ProviderType createProviderType() {
        return new ProviderType();
    }

    /**
     * Create an instance of {@link ParameterListType }
     * 
     */
    public ParameterListType createParameterListType() {
        return new ParameterListType();
    }

    /**
     * Create an instance of {@link ProviderListType }
     * 
     */
    public ProviderListType createProviderListType() {
        return new ProviderListType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3schools.com", name = "config")
    public JAXBElement<ConfigType> createConfig(ConfigType value) {
        return new JAXBElement<ConfigType>(_Config_QNAME, ConfigType.class, null, value);
    }

}
