//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.11 at 11:32:44 PM CEST 
//


package com.jtalis.core.config.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="debug" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="consult" type="{http://www.w3schools.com}ConsultFilesListType" minOccurs="0"/>
 *         &lt;element name="flags" type="{http://www.w3schools.com}EtalisFlagsListType" minOccurs="0"/>
 *         &lt;element name="predicates" type="{http://www.w3schools.com}PredicatesListType" minOccurs="0"/>
 *         &lt;element name="compileEventFiles" type="{http://www.w3schools.com}EventFilesListType" minOccurs="0"/>
 *         &lt;element name="eventTriggers" type="{http://www.w3schools.com}EventTriggersListType" minOccurs="0"/>
 *         &lt;element name="eventRules" type="{http://www.w3schools.com}EventRuleListType" minOccurs="0"/>
 *         &lt;element name="providers" type="{http://www.w3schools.com}ProviderListType" minOccurs="0"/>
 *         &lt;element name="outputQueues" type="{http://www.w3schools.com}OutputQueuesListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigType", propOrder = {
    "debug",
    "consult",
    "flags",
    "predicates",
    "compileEventFiles",
    "eventTriggers",
    "eventRules",
    "providers",
    "outputQueues"
})
public class ConfigType {

    protected Boolean debug;
    protected ConsultFilesListType consult;
    protected EtalisFlagsListType flags;
    protected PredicatesListType predicates;
    protected EventFilesListType compileEventFiles;
    protected EventTriggersListType eventTriggers;
    protected EventRuleListType eventRules;
    protected ProviderListType providers;
    protected OutputQueuesListType outputQueues;

    /**
     * Gets the value of the debug property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDebug() {
        return debug;
    }

    /**
     * Sets the value of the debug property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDebug(Boolean value) {
        this.debug = value;
    }

    /**
     * Gets the value of the consult property.
     * 
     * @return
     *     possible object is
     *     {@link ConsultFilesListType }
     *     
     */
    public ConsultFilesListType getConsult() {
        return consult;
    }

    /**
     * Sets the value of the consult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsultFilesListType }
     *     
     */
    public void setConsult(ConsultFilesListType value) {
        this.consult = value;
    }

    /**
     * Gets the value of the flags property.
     * 
     * @return
     *     possible object is
     *     {@link EtalisFlagsListType }
     *     
     */
    public EtalisFlagsListType getFlags() {
        return flags;
    }

    /**
     * Sets the value of the flags property.
     * 
     * @param value
     *     allowed object is
     *     {@link EtalisFlagsListType }
     *     
     */
    public void setFlags(EtalisFlagsListType value) {
        this.flags = value;
    }

    /**
     * Gets the value of the predicates property.
     * 
     * @return
     *     possible object is
     *     {@link PredicatesListType }
     *     
     */
    public PredicatesListType getPredicates() {
        return predicates;
    }

    /**
     * Sets the value of the predicates property.
     * 
     * @param value
     *     allowed object is
     *     {@link PredicatesListType }
     *     
     */
    public void setPredicates(PredicatesListType value) {
        this.predicates = value;
    }

    /**
     * Gets the value of the compileEventFiles property.
     * 
     * @return
     *     possible object is
     *     {@link EventFilesListType }
     *     
     */
    public EventFilesListType getCompileEventFiles() {
        return compileEventFiles;
    }

    /**
     * Sets the value of the compileEventFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventFilesListType }
     *     
     */
    public void setCompileEventFiles(EventFilesListType value) {
        this.compileEventFiles = value;
    }

    /**
     * Gets the value of the eventTriggers property.
     * 
     * @return
     *     possible object is
     *     {@link EventTriggersListType }
     *     
     */
    public EventTriggersListType getEventTriggers() {
        return eventTriggers;
    }

    /**
     * Sets the value of the eventTriggers property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventTriggersListType }
     *     
     */
    public void setEventTriggers(EventTriggersListType value) {
        this.eventTriggers = value;
    }

    /**
     * Gets the value of the eventRules property.
     * 
     * @return
     *     possible object is
     *     {@link EventRuleListType }
     *     
     */
    public EventRuleListType getEventRules() {
        return eventRules;
    }

    /**
     * Sets the value of the eventRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventRuleListType }
     *     
     */
    public void setEventRules(EventRuleListType value) {
        this.eventRules = value;
    }

    /**
     * Gets the value of the providers property.
     * 
     * @return
     *     possible object is
     *     {@link ProviderListType }
     *     
     */
    public ProviderListType getProviders() {
        return providers;
    }

    /**
     * Sets the value of the providers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProviderListType }
     *     
     */
    public void setProviders(ProviderListType value) {
        this.providers = value;
    }

    /**
     * Gets the value of the outputQueues property.
     * 
     * @return
     *     possible object is
     *     {@link OutputQueuesListType }
     *     
     */
    public OutputQueuesListType getOutputQueues() {
        return outputQueues;
    }

    /**
     * Sets the value of the outputQueues property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputQueuesListType }
     *     
     */
    public void setOutputQueues(OutputQueuesListType value) {
        this.outputQueues = value;
    }

}
